remote_theme: Drassil/git-wiki
title: [LApIS wiki]
description: [Wiki do Laboratório de Aplicações de Informática em Saúde]
logo_url: http://lapis.each.usp.br/wiki/assets/images/logo.png
custom_sidebar: true
