remote_theme: Drassil/git-wiki
title: [LApIS wiki]
description: [Wiki do Laboratório de Aplicações de Informática em Saúde]
logo_url: https://raw.githubusercontent.com/lapisusp/lapisusp.github.io/master/assets/images/logo.png
custom_sidebar: true
