---
title: LApIS wiki
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: wiki
  values:
    permalink: "/:basename"
- scope:
    path: ''
  values:
    layout: git-wiki-default
- scope:
    path: ''
    type: pages
  values:
    layout: git-wiki-default
- scope:
    path: ''
    type: posts
  values:
    layout: git-wiki-post
- scope:
    path: blog
  values:
    layout: git-wiki-blog
description: Wiki do Laboratório de Aplicações de Informática em Saúde
show_wiki_pages: true
show_wiki_pages_limit: 5
blog_feature: false
show_wiki_posts: false
show_wiki_posts_limit: 5
paginate: 20
paginate_path: "/blog/page:num"
permalink: "/blog/posts/:year/:month/:day/:title:output_ext"
show_downloads: false
git_branch: master
logo_url: assets/images/logo.png
google_analytics: 
url: http://lapis.each.usp.br
wiki_folder: wiki
use_github_wiki: false
use_prose_io: false
search_engine: js
google_cse_token: 
sass:
  style: compressed
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-avatar
- jemoji
- jekyll-mentions
inc_before_toc: 
inc_after_toc: 
inc_before_content: 
inc_after_content: 
inc_before_footer: 
inc_after_footer: 
inc_before_head: 
inc_after_head: 
inc_before_meta: 
inc_after_meta: 
inc_before_scripts: 
inc_after_scripts: 
inc_before_styles: 
inc_after_styles: 
inc_before_header: 
inc_after_header: 
inc_before_tail: 
inc_after_tail: 
inc_before_tools: 
inc_after_tools: 
inc_before_page_list: custom/sidebar.html
inc_after_page_list: 
inc_before_post_list: 
inc_after_post_list: 
