remote_theme: Drassil/git-wiki
title: [LApIS wiki]
description: [Wiki do Laboratório de Aplicações de Informática em Saúde]
logo_url: http://lapis.each.usp.br/wp-content/uploads/2016/01/lapis-2016-1.png
custom_sidebar: true
